### ISSUE TITLE
yo phaser crash when selecting Phaser version

### ISSUE THREAD

**Issue by derrickroccka** [julien/generator-phaser#33]
hi! I've recently installed this generator but when I select the Phaser version this is what I get:

> ? Which version of Phaser do you want? Arcade Physics 
+ P2 Physics (Default)
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: /usr/local/lib/node_modules/generator-phaser/generators/app/templates/_package.json:2
    1| {
 >> 2|   "name": "<%= _.slugify(projectName) %>",
    3|   "description": "",
    4|   "readme": "",
    5|   "repository": "",

Cannot read property 'slugify' of undefined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/generator-phaser/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:11:24)
    at returnedFn (/usr/local/lib/node_modules/generator-phaser/node_modules/ejs/lib/ejs.js:514:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-phaser/node_modules/ejs/lib/ejs.js:316:37)
    at copy.process (/usr/local/lib/node_modules/generator-phaser/node_modules/mem-fs-editor/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-phaser/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-phaser/node_modules/mem-fs-editor/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-phaser/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-phaser/node_modules/mem-fs-editor/actions/copy-tpl.js:12:8)
    at template (/usr/local/lib/node_modules/generator-phaser/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at generators.Base.extend.app (/usr/local/lib/node_modules/generator-phaser/generators/app/index.js:65:10)

Could you help me???
Thank you :)

**Comment by julien** [comment]
Hi @derrickroccka, I'm aware of this, I accidently pushed a bad version yesterday, there are some changes but if you reinstall the latest version that should be fixed

**Comment by derrickroccka** [comment]
I was just doing it and I came back to say that everything is fine now haha thanks for all @julien ! I'm eager to start with Phaser :)
